wandb_version: 1

learning_rate:
  desc: null
  value: 0
optimizer:
  desc: null
  value: ''
dataset:
  desc: null
  value: ''
model_architecture:
  desc: null
  value: ''
batch_size:
  desc: null
  value: 0
epochs:
  desc: null
  value: 0
num_rounds:
  desc: null
  value: 0
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: huggingface
    huggingface_version: 4.39.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1719301290.0
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 30
      - 41
      - 49
      - 50
      - 53
      - 55
      2:
      - 1
      - 2
      - 3
      - 5
      - 11
      - 30
      - 41
      - 49
      - 50
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.11.5
      5: 0.16.6
      6: 4.39.2
      8:
      - 5
      13: linux-x86_64
